name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:
  build: 
    runs-on: ubuntu-16.04
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build -f DocumentAPI/Dockerfile --tag document-api:$(date +%s) .
    - name: Push Image to ECR
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        REPOSITORY_URL: 979207732266.dkr.ecr.us-east-2.amazonaws.com/dpd-document-api
      run: |
        $(aws ecr get-login --no-include-email --region us-east-1)
        docker tag api_api:latest $REPOSITORY_URL:$(date +%s)
        docker push $REPOSITORY_URL:$(date +%s)
    - name: Deploy to Fargate
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        REPOSITORY_URL: 979207732266.dkr.ecr.us-east-2.amazonaws.com/dpd-document-api
      run: | 
        aws ecs update-service --cluster dpd-document-api-cluster --service dpd-document-api-container-service --force-new-deployment --region us-east-1  
