name: Test, Build and deploy to TEST
on:
  push:
    branches:
      - master
jobs:
  build-image-and-deploy:
    needs: build-and-test
    runs-on: ubuntu-16.04
    env:
      config: 'Release'
    steps:
    # build docker image
    - name: Build the Docker image
      run: docker build -f DocumentAPI/Dockerfile -t dpd-document-api:test-latest .
    - name: Push Image to ECR (Test)
      env:
        ASPNETCORE_ENVIRONMENT: 'Test'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        REPOSITORY_URL: 922311303087.dkr.ecr.us-east-1.amazonaws.com/dpd-document-api
      run: |
        $(aws ecr get-login --no-include-email --region us-east-1)
        docker tag dpd-document-api:test-latest $REPOSITORY_URL:test-latest
        docker push $REPOSITORY_URL:test-latest
    - name: Deploy to Fargate
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        REPOSITORY_URL: 922311303087.dkr.ecr.us-east-1.amazonaws.com/dpd-document-api
      run: |
        aws ecs update-service --cluster dpd-document-api-test-cluster --service dpd-document-api-test-service --force-new-deployment --region us-east-1
